### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jannickfahlbusch** [jannickfahlbusch/magic-filetransfer#2]
* [ ] Progressbar
* [ ] Ability to specify destination of the transferred file (and even the output name)
* [ ] Ability to specify multiple files
* [ ] Ability to specify a whole directory
